/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 92e662b0cc4fe655a53f7f2bd3651820)
interface __BaseEnv_Env {
	OAUTH_SESSION: KVNamespace;
	OAUTH_STATE: KVNamespace;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
