import { readFileSync, writeFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

import { TEAMS } from '../src/lib/tournament/data.ts'

/**
 * Copies the Flagpack (flagpack-core) medium SVG for each World Cup team
 * into src/lib/tournament/flags.generated.ts, so only the ~48 flags we use
 * ship rather than the whole 250-flag set. The team→ISO mapping lives in
 * data.ts (single source of truth). Run: pnpm gen:flags
 *
 * Flagpack SVGs are self-contained documents (with their own viewBox and
 * clip-path ids), so flags.ts renders them as isolated <img> data URIs —
 * which also sidesteps id collisions between the many flags on a page.
 */

const require = createRequire(import.meta.url)
const SVG_DIR = `${dirname(require.resolve('flagpack-core/package.json'))}/svg/m`

const svgs: Record<string, string> = {}
const missing: string[] = []
for (const team of Object.values(TEAMS)) {
  try {
    // flagpack-core files are named by UPPERCASE ISO (e.g. US.svg, GB-ENG.svg).
    svgs[team.iso] = readFileSync(`${SVG_DIR}/${team.iso.toUpperCase()}.svg`, 'utf8').trim()
  }
  catch {
    missing.push(team.iso)
  }
}

if (missing.length > 0) {
  throw new Error(`flagpack-core is missing flags for: ${missing.join(', ')}`)
}

const out = `// GENERATED by scripts/gen-flags.ts — do not edit by hand.
// Flagpack (flagpack-core) medium SVGs for each World Cup team, kept as a
// subset so the full 250-flag set stays out of the bundle. Rendered as <img>
// data URIs (flags.ts) since the SVGs carry their own ids.
// Regenerate after changing team ISO codes in data.ts: pnpm gen:flags

export const FLAG_SVG: Record<string, string> = ${JSON.stringify(svgs)}
`

const dir = dirname(fileURLToPath(import.meta.url))
writeFileSync(resolve(dir, '../src/lib/tournament/flags.generated.ts'), out)
console.log(`Wrote ${Object.keys(svgs).length} Flagpack flags`)
