/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OauthCallbackRouteImport } from './routes/oauth.callback'
import { Route as BHandleRouteImport } from './routes/b.$handle'
import { Route as BHandleOgDotpngRouteImport } from './routes/b.$handle.og[.]png'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthCallbackRoute = OauthCallbackRouteImport.update({
  id: '/oauth/callback',
  path: '/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const BHandleRoute = BHandleRouteImport.update({
  id: '/b/$handle',
  path: '/b/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const BHandleOgDotpngRoute = BHandleOgDotpngRouteImport.update({
  id: '/og.png',
  path: '/og.png',
  getParentRoute: () => BHandleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/b/$handle': typeof BHandleRouteWithChildren
  '/oauth/callback': typeof OauthCallbackRoute
  '/b/$handle/og.png': typeof BHandleOgDotpngRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/b/$handle': typeof BHandleRouteWithChildren
  '/oauth/callback': typeof OauthCallbackRoute
  '/b/$handle/og.png': typeof BHandleOgDotpngRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/b/$handle': typeof BHandleRouteWithChildren
  '/oauth/callback': typeof OauthCallbackRoute
  '/b/$handle/og.png': typeof BHandleOgDotpngRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/b/$handle' | '/oauth/callback' | '/b/$handle/og.png'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/b/$handle' | '/oauth/callback' | '/b/$handle/og.png'
  id: '__root__' | '/' | '/b/$handle' | '/oauth/callback' | '/b/$handle/og.png'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BHandleRoute: typeof BHandleRouteWithChildren
  OauthCallbackRoute: typeof OauthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/callback': {
      id: '/oauth/callback'
      path: '/oauth/callback'
      fullPath: '/oauth/callback'
      preLoaderRoute: typeof OauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b/$handle': {
      id: '/b/$handle'
      path: '/b/$handle'
      fullPath: '/b/$handle'
      preLoaderRoute: typeof BHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b/$handle/og.png': {
      id: '/b/$handle/og.png'
      path: '/og.png'
      fullPath: '/b/$handle/og.png'
      preLoaderRoute: typeof BHandleOgDotpngRouteImport
      parentRoute: typeof BHandleRoute
    }
  }
}

interface BHandleRouteChildren {
  BHandleOgDotpngRoute: typeof BHandleOgDotpngRoute
}

const BHandleRouteChildren: BHandleRouteChildren = {
  BHandleOgDotpngRoute: BHandleOgDotpngRoute,
}

const BHandleRouteWithChildren =
  BHandleRoute._addFileChildren(BHandleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BHandleRoute: BHandleRouteWithChildren,
  OauthCallbackRoute: OauthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
