/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BracketRouteImport } from './routes/bracket'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GroupsIndexRouteImport } from './routes/groups.index'
import { Route as OauthCallbackRouteImport } from './routes/oauth.callback'
import { Route as GroupsThirdsRouteImport } from './routes/groups.thirds'
import { Route as GroupsGroupIdRouteImport } from './routes/groups.$groupId'
import { Route as BHandleRouteImport } from './routes/b.$handle'
import { Route as BHandleOgDotpngRouteImport } from './routes/b.$handle.og[.]png'

const BracketRoute = BracketRouteImport.update({
  id: '/bracket',
  path: '/bracket',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsIndexRoute = GroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthCallbackRoute = OauthCallbackRouteImport.update({
  id: '/oauth/callback',
  path: '/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsThirdsRoute = GroupsThirdsRouteImport.update({
  id: '/groups/thirds',
  path: '/groups/thirds',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGroupIdRoute = GroupsGroupIdRouteImport.update({
  id: '/groups/$groupId',
  path: '/groups/$groupId',
  getParentRoute: () => rootRouteImport,
} as any)
const BHandleRoute = BHandleRouteImport.update({
  id: '/b/$handle',
  path: '/b/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const BHandleOgDotpngRoute = BHandleOgDotpngRouteImport.update({
  id: '/og.png',
  path: '/og.png',
  getParentRoute: () => BHandleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bracket': typeof BracketRoute
  '/b/$handle': typeof BHandleRouteWithChildren
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/groups/thirds': typeof GroupsThirdsRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/groups/': typeof GroupsIndexRoute
  '/b/$handle/og.png': typeof BHandleOgDotpngRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bracket': typeof BracketRoute
  '/b/$handle': typeof BHandleRouteWithChildren
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/groups/thirds': typeof GroupsThirdsRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/groups': typeof GroupsIndexRoute
  '/b/$handle/og.png': typeof BHandleOgDotpngRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bracket': typeof BracketRoute
  '/b/$handle': typeof BHandleRouteWithChildren
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/groups/thirds': typeof GroupsThirdsRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/groups/': typeof GroupsIndexRoute
  '/b/$handle/og.png': typeof BHandleOgDotpngRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bracket'
    | '/b/$handle'
    | '/groups/$groupId'
    | '/groups/thirds'
    | '/oauth/callback'
    | '/groups/'
    | '/b/$handle/og.png'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bracket'
    | '/b/$handle'
    | '/groups/$groupId'
    | '/groups/thirds'
    | '/oauth/callback'
    | '/groups'
    | '/b/$handle/og.png'
  id:
    | '__root__'
    | '/'
    | '/bracket'
    | '/b/$handle'
    | '/groups/$groupId'
    | '/groups/thirds'
    | '/oauth/callback'
    | '/groups/'
    | '/b/$handle/og.png'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BracketRoute: typeof BracketRoute
  BHandleRoute: typeof BHandleRouteWithChildren
  GroupsGroupIdRoute: typeof GroupsGroupIdRoute
  GroupsThirdsRoute: typeof GroupsThirdsRoute
  OauthCallbackRoute: typeof OauthCallbackRoute
  GroupsIndexRoute: typeof GroupsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/bracket': {
      id: '/bracket'
      path: '/bracket'
      fullPath: '/bracket'
      preLoaderRoute: typeof BracketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/': {
      id: '/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof GroupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/callback': {
      id: '/oauth/callback'
      path: '/oauth/callback'
      fullPath: '/oauth/callback'
      preLoaderRoute: typeof OauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/thirds': {
      id: '/groups/thirds'
      path: '/groups/thirds'
      fullPath: '/groups/thirds'
      preLoaderRoute: typeof GroupsThirdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId': {
      id: '/groups/$groupId'
      path: '/groups/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof GroupsGroupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b/$handle': {
      id: '/b/$handle'
      path: '/b/$handle'
      fullPath: '/b/$handle'
      preLoaderRoute: typeof BHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b/$handle/og.png': {
      id: '/b/$handle/og.png'
      path: '/og.png'
      fullPath: '/b/$handle/og.png'
      preLoaderRoute: typeof BHandleOgDotpngRouteImport
      parentRoute: typeof BHandleRoute
    }
  }
}

interface BHandleRouteChildren {
  BHandleOgDotpngRoute: typeof BHandleOgDotpngRoute
}

const BHandleRouteChildren: BHandleRouteChildren = {
  BHandleOgDotpngRoute: BHandleOgDotpngRoute,
}

const BHandleRouteWithChildren =
  BHandleRoute._addFileChildren(BHandleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BracketRoute: BracketRoute,
  BHandleRoute: BHandleRouteWithChildren,
  GroupsGroupIdRoute: GroupsGroupIdRoute,
  GroupsThirdsRoute: GroupsThirdsRoute,
  OauthCallbackRoute: OauthCallbackRoute,
  GroupsIndexRoute: GroupsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
